### ISSUE TITLE
tut input

### ISSUE THREAD

**Issue by Youssef-Ashraf2099** [GIU-Connect/GIU-Connect#1]
![max 20tut](https://github.com/user-attachments/assets/30487693-2d36-47a4-938a-28f88c3de041)

**Comment by momenashrafff** [comment]
Hello *Youssef*,

Thank you for your message! We will be updating the tutorial input to limit the selection from 1 to the maximum number of tutorials available for each major in the next update.

If I misunderstood your request, could you kindly clarify further? Your input is greatly appreciated!

Best regards,
*Momen Ashraf Elkhouli*
